version:  '3'
services:
  mc-server:
    image: mincraft-public-survival-server
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - .:/server
      - /server/world
      - /server/world_nether
      - /server/world_the_end
    working_dir: /server
    ports:
      - '25565:25565'
    command: >
      /bin/sh -c "echo 'RUNNING' & while sleep 60000; do :; done"